const KEYWORDS = [
  'ant',
  'basket',
  'bells',
  'bucket',
  // 'building',
  // 'calendar',
  // 'carpenter',
  // 'cart',
  // 'cemetery',
  // 'chance',
  // 'chicken',
  // 'chin',
  // 'club',
  // 'country',
  // 'deer',
  // 'dime',
  // 'dinosaurs',
  // 'expansion',
  // 'fall',
  // 'fire',
  // 'flag',
  // 'flower',
  // 'fork',
  // 'group',
  // 'guide',
  // 'jump',
  // 'kitty',
  // 'lamp',
  // 'land',
  // 'line',
  // 'meal',
  // 'milk',
  // 'morning',
  // 'move',
  // 'pan',
  // 'party',
  // 'price',
  // 'rest',
  // 'scarf',
  // 'school',
  // 'shape',
  // 'skate',
  // 'snails',
  // 'sneeze',
  // 'soap',
  // 'spark',
  // 'spot',
  // 'stretch',
  // 'surprise',
  // 'table',
  // 'tomatoes',
  // 'tray',
  // 'tree',
  // 'trucks',
  // 'tub',
  // 'vessel',
  // 'volleyball',
  // 'waves',
  // 'wealth',
  // 'wind',
  // 'window'
];

export const randomNoun = () => {
  return KEYWORDS[Math.floor(Math.random()*KEYWORDS.length)];
};